export const BRAND = 'StatPitch'

export const DISCLAIMER = {
  short: 'For informational purposes only.',
  body: `${BRAND} does not facilitate, encourage, or endorse any form of gambling or wagering.`,
  extended:
    'All probability outputs are generated by statistical models and reflect historical patterns — they are not guarantees of future results. The platform and its operators accept no responsibility for financial decisions made based on this data. If you or someone you know has a gambling problem, please seek help at begambleaware.org.',
}

/**
 * What to say about a competition that is served, predicted and priced in full
 * and still cannot produce a bet.
 *
 * One wording, used everywhere the question comes up, because the alternative
 * is three surfaces each inventing their own and one of them landing on "no
 * picks today" — which describes a quiet day, reads as a fault, and is neither.
 * The API cannot help here: an unstakeable league and a quiet day both come
 * back as `NO_QUALIFYING_SELECTION`.
 */
export const OUTSIDE_SCOPE = {
  short: 'Predictions only',
  title: 'Served and priced in full — outside the scope the selection rule was measured on',
  body: 'This competition is predicted and priced in full, and sits outside the scope the selection rule was measured on. No bet is expected here.',
}
