export const BRAND = 'StatPitch'

export const MODEL = {
  /** Used when a prediction payload carries no model_version of its own. */
  fallbackVersion: 'v4',
  ensemble: 'Gradient Boost + Neural Net Ensemble',
}

export const DISCLAIMER = {
  short: 'For informational purposes only.',
  body: `${BRAND} does not facilitate, encourage, or endorse any form of gambling or wagering.`,
  extended:
    'All probability outputs are generated by statistical models and reflect historical patterns — they are not guarantees of future results. The platform and its operators accept no responsibility for financial decisions made based on this data. If you or someone you know has a gambling problem, please seek help at begambleaware.org.',
}

/**
 * Marketing figures shown on the login and pricing pages.
 * These are hardcoded claims, not live API values — keep them in sync with published results.
 */
export const MARKETING_STATS = {
  accuracy: '71.4%',
  roi: '+8.3%',
  marketsCovered: '1,200+',
  leagues: '38',
  predictionsPublished: '24,000+',
}

/** The API does not yet return a competition name per fixture. */
export const DEFAULT_COMPETITION = 'FIFA World Cup'
