export const BRAND = 'StatPitch'

export const MODEL = {
  /** Only reached when the fixture list is empty; every fixture carries its own. */
  fallbackVersion: 'unknown',
}

export const DISCLAIMER = {
  short: 'For informational purposes only.',
  body: `${BRAND} does not facilitate, encourage, or endorse any form of gambling or wagering.`,
  extended:
    'All probability outputs are generated by statistical models and reflect historical patterns — they are not guarantees of future results. The platform and its operators accept no responsibility for financial decisions made based on this data. If you or someone you know has a gambling problem, please seek help at begambleaware.org.',
}
