import { useState } from 'react'

function Footer() {
  const [isOpened, setIsOpened] = useState(false)
  return (
    <footer
      className={
        'container mx-auto bg-background text-foreground text-center py-2 lg:py-0 h-fit gap-12 justify-between flex flex-col px-2 mt-16'
      }
    >
      <div className={'border-t border-secondary-foreground/10 pt-4 w-screen self-center'}>
        <div className={'container mx-auto flex flex-col justify-between items-center lg:flex-row'}>
          <p
            className={
              'text-xs text-secondary-foreground/60 lg:shrink-0 text-start pb-4 px-4 lg:px-0 lg:max-w-10/12'
            }
          >
            <span className={'text-secondary-foreground'}>For informational purposes only.</span>{' '}
            StatPitch does not facilitate, encourage, or endorse any form of gambling or wagering.{' '}
            <span className={`${isOpened ? 'inline' : 'hidden'}`}>
              All probability outputs are generated by statistical models and reflect historical
              patterns — they are not guarantees of future results. The platform and its operators
              accept no responsibility for financial decisions made based on this data. If you or
              someone you know has a gambling problem, please seek help at begambleaware.org.{' '}
            </span>
            <span
              className={`text-secondary-foreground underline cursor-pointer ${isOpened ? 'hidden' : ''}`}
              onClick={() => setIsOpened(true)}
            >
              Read more
            </span>
            <span
              className={`text-secondary-foreground underline cursor-pointer ${isOpened ? '' : 'hidden'}`}
              onClick={() => setIsOpened(false)}
            >
              Less
            </span>
          </p>
          <p className={'text-xs text-secondary-foreground/60'}>© 2026 StatPitch</p>
        </div>
      </div>
    </footer>
  )
}

export default Footer
