export function buildMarkets(prediction) {
  return [
    {
      key: 'home_win',
      market: prediction.home_team + ' Win',
      ev: prediction.ev_home,
      odds: prediction.odds_home,
      prob: prediction.home_win_prob,
      kelly: prediction.kelly_home,
    },
    {
      key: 'draw',
      market: 'Draw',
      ev: prediction.ev_draw,
      odds: prediction.odds_draw,
      prob: prediction.draw_prob,
      kelly: prediction.kelly_draw,
    },
    {
      key: 'away_win',
      market: prediction.away_team + ' Win',
      ev: prediction.ev_away,
      odds: prediction.odds_away,
      prob: prediction.away_win_prob,
      kelly: prediction.kelly_away,
    },
    {
      key: 'btts_yes',
      market: 'Both Teams to Score (Yes)',
      ev: prediction.ev_btts_yes,
      odds: prediction.odds_btts_yes,
      prob: prediction.btts_yes,
      kelly: prediction.kelly_btts_yes,
    },
    {
      key: 'btts_no',
      market: 'Both Teams to Score (No)',
      ev: prediction.ev_btts_no,
      odds: prediction.odds_btts_no,
      prob: prediction.btts_no,
      kelly: prediction.kelly_btts_no,
    },
    {
      key: 'over_1_5',
      market: 'Over 1.5 Goals',
      ev: prediction.ev_over_1_5,
      odds: prediction.odds_over_1_5,
      prob: prediction.over_1_5,
      kelly: prediction.kelly_over_1_5,
    },
    {
      key: 'over_2_5',
      market: 'Over 2.5 Goals',
      ev: prediction.ev_over_2_5,
      odds: prediction.odds_over_2_5,
      prob: prediction.over_2_5,
      kelly: prediction.kelly_over_2_5,
    },
    {
      key: 'over_3_5',
      market: 'Over 3.5 Goals',
      ev: prediction.ev_over_3_5,
      odds: prediction.odds_over_3_5,
      prob: prediction.over_3_5,
      kelly: prediction.kelly_over_3_5,
    },
    {
      key: 'under_1_5',
      market: 'Under 1.5 Goals',
      ev: prediction.ev_under_1_5,
      odds: prediction.odds_under_1_5,
      prob: prediction.under_1_5,
      kelly: prediction.kelly_under_1_5,
    },
    {
      key: 'under_2_5',
      market: 'Under 2.5 Goals',
      ev: prediction.ev_under_2_5,
      odds: prediction.odds_under_2_5,
      prob: prediction.under_2_5,
      kelly: prediction.kelly_under_2_5,
    },
    {
      key: 'under_3_5',
      market: 'Under 3.5 Goals',
      ev: prediction.ev_under_3_5,
      odds: prediction.odds_under_3_5,
      prob: prediction.under_3_5,
      kelly: prediction.kelly_under_3_5,
    },
  ]
}
