export const pricingPlans = [
  {
    name: 'Free',
    description: 'Get a feel for the model',
    price: 'Free',
    period: null,
    isPopular: false,
    buttonText: 'Start free',
    buttonLink: '/login',
    availableFeatures: [
      '3 predictions per day',
      'Top 5 leagues only',
      '1X2 win probabilities',
      'Match of the Day pick',
    ],
    notAvailableFeatures: [
      'Market breakdown (Book vs ML)',
      'Edge & value indicators',
      'AI confidence scoring',
      'Historical accuracy stats',
      'API access',
    ],
  },
  {
    name: 'Pro',
    description: 'For serious bettors',
    price: '$29',
    period: '/mo',
    isPopular: true,
    buttonText: 'Start 14-day trial',
    buttonLink: '/login',
    availableFeatures: [
      'Unlimited predictions',
      '38 leagues & competitions',
      '1X2 win probabilities',
      'Match of the Day pick',
      'Market breakdown (Book vs ML)',
      'Edge & value indicators',
      'AI confidence scoring',
      'Historical accuracy stats',
    ],
    notAvailableFeatures: ['API access'],
  },
  {
    name: 'Elite',
    description: 'Maximum edge, raw access',
    price: '$79',
    period: '/mo',
    isPopular: false,
    buttonText: 'Contact us',
    buttonLink: '/login',
    availableFeatures: [
      'Unlimited predictions',
      '38 leagues & competitions',
      '1X2 win probabilities',
      'Match of the Day pick',
      'Market breakdown (Book vs ML)',
      'Edge & value indicators',
      'AI confidence scoring',
      'Historical accuracy stats',
      'API access',
    ],
    notAvailableFeatures: [],
  },
]
